In [2]:
# hide warnings
import warnings
warnings.filterwarnings('ignore')

# https://groups.csail.mit.edu/sls/downloads/restaurant/

In [3]:
!pip install -U transformers
!pip install -U accelerate
!pip install -U datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.3.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.3.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.3.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Downloading datasets-4.5.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 32.5 MB/s eta 0:00:00
Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 13.1 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-4.5.0 pyarrow-23.0.0

In [4]:
import pandas as pd
import json
import requests

In [5]:
train = pd.read_csv("https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/mit_restaurant_search_ner/train.bio", sep="\t", header=None)
train.head()

           0            1
0   B-Rating            2
1   I-Rating        start
2          O  restaurants
3          O         with
4  B-Amenity       inside

In [6]:
response = requests.get("https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/mit_restaurant_search_ner/train.bio")
response = response.text

In [7]:
response = response.splitlines()

In [8]:
response[:]

['B-Rating\t2',
 'I-Rating\tstart',
 'O\trestaurants',
 'O\twith',
 'B-Amenity\tinside',
 'I-Amenity\tdining',
 '',
 'O\t34',
 '',
 'B-Rating\t5',
 'I-Rating\tstar',
 'O\tresturants',
 'B-Location\tin',
 'I-Location\tmy',
 'I-Location\ttown',
 '',
 'O\t98',
 'B-Restaurant_Name\thong',
 'I-Restaurant_Name\tkong',
 'O\trestaurant',
 'B-Price\treasonable',
 'O\tprices',
 '',
 'O\ta',
 'O\tgreat',
 'O\tlunch',
 'O\tspot',
 'O\tbut',
 'B-Hours\topen',
 'I-Hours\ttill',
 'I-Hours\t2',
 'I-Hours\ta',
 'I-Hours\tm',
 'B-Restaurant_Name\tpassims',
 'I-Restaurant_Name\tkitchen',
 '',
 'O\ta',
 'O\tplace',
 'O\tthat',
 'O\tserves',
 'B-Dish\tsoft',
 'I-Dish\tserve',
 'I-Dish\tice',
 'I-Dish\tcream',
 '',
 'O\ta',
 'O\trestaurant',
 'O\tthat',
 'O\tis',
 'B-Rating\tgood',
 'B-Amenity\tfor',
 'I-Amenity\tgroups',
 '',
 'O\ta',
 'B-Dish\tsalad',
 'O\twould',
 'O\tmake',
 'O\tmy',
 'O\tday',
 '',
 'O\ta',
 'B-Cuisine\tsmoothie',
 'O\twould',
 'O\thit',
 'O\tthe',
 'O\tspot',
 '',
 'O\ta',
 'B-Dish\tsteak',
 'O\twould',
 'O\tbe',
 'O\tnice',
 '',
 'O\ta',
 'B-Dish\tsub',
 'O\tplace',
 'B-Location\tnear',
 'I-Location\tindependence',
 'I-Location\tboulevard',
 '',
 'O\tabout',
 'O\thow',
 'O\tmuch',
 'O\tis',
 'O\ta',
 'B-Price\tmidpriced',
 'B-Rating\tbottle',
 'O\tof',
 'B-Rating\tgood',
 'B-Cuisine\twine',
 'O\tat',
 'B-Restaurant_Name\tdavidos',
 'I-Restaurant_Name\titalian',
 'I-Restaurant_Name\tpalace',
 '',
 'O\tabout',
 'O\thow',
 'O\tmuch',
 'O\twill',
 'O\tit',
 'B-Price\tcost',
 'O\tto',
 'O\teat',
 'O\tat',
 'B-Restaurant_Name\tjohns',
 'I-Restaurant_Name\tpizza',
 'I-Restaurant_Name\tcafe',
 'O\tfor',
 'B-Hours\tdinner',
 'B-Price\tper',
 'I-Price\tperson',
 '',
 'O\tadress',
 'O\tof',
 'O\tthe',
 'B-Location\tnearest',
 'B-Restaurant_Name\tcracker',
 'I-Restaurant_Name\tbarrel',
 '',
 'B-Hours\tafter',
 'I-Hours\thour',
 'I-Hours\tdining',
 '',
 'O\tall',
 'O\ti',
 'O\twant',
 'O\tis',
 'O\ta',
 'B-Dish\tbagel',
 'I-Dish\tand',
 'I-Dish\tcoffee',
 'O\tcan',
 'O\tyou',
 'O\tdirect',
 'O\tme',
 '',
 'O\tall',
 'O\ti',
 'O\twant',
 'O\tis',
 'B-Dish\tsalmon',
 '',
 'O\tall',
 'O\ti',
 'O\twant',
 'O\tis',
 'O\tsome',
 'B-Dish\tfresh',
 'I-Dish\tfruits',
 'O\twhere',
 'O\tis',
 'O\tthe',
 'B-Location\tnearest',
 'I-Location\tsupermarket',
 '',
 'O\tall',
 'O\ti',
 'O\twant',
 'O\tis',
 'O\tsome',
 'B-Rating\tgood',
 'B-Dish\tchili',
 'O\tcan',
 'O\tyou',
 'O\thelp',
 'O\tme',
 'O\tfind',
 'O\tthat',
 '',
 'O\talong',
 'O\tmy',
 'O\troute',
 'O\ttell',
 'O\tme',
 'O\tthe',
 'O\tnext',
 'B-Cuisine\tsteak',
 'I-Cuisine\thouse',
 'O\tthat',
 'O\tis',
 'B-Location\twithin',
 'I-Location\ta',
 'I-Location\tmile',
 '',
 'O\talot',
 'O\tof',
 'B-Amenity\tparking',
 'B-Cuisine\tindian',
 'O\tfood',
 '',
 'O\talthough',
 'O\ta',
 'B-Rating\tgood',
 'B-Dish\tburger',
 'O\twould',
 'O\tbe',
 'O\tgood',
 'O\ttime',
 'O\tfor',
 'B-Restaurant_Name\tburger',
 'I-Restaurant_Name\tking',
 '',
 'O\tam',
 'O\ti',
 'O\tablle',
 'O\tto',
 'O\tget',
 'O\ta',
 'O\treservation',
 'O\tat',
 'B-Restaurant_Name\tmcdills',
 'B-Hours\ttonight',
 '',
 'B-Cuisine\tamerican',
 'O\tstyle',
 'O\trestaurants',
 'B-Rating\treviews',
 '',
 'B-Amenity\tanniversary',
 'I-Amenity\tdinner',
 '',
 'O\tany',
 'B-Amenity\t50s',
 'I-Amenity\tstyle',
 'B-Cuisine\tdiners',
 'O\taround',
 '',
 'O\tany',
 'B-Cuisine\tbars',
 'O\taround',
 'O\tthat',
 'O\tare',
 'B-Hours\topen',
 'I-Hours\tbefore',
 'I-Hours\t11',
 'I-Hours\ta',
 'I-Hours\tm',
 '',
 'O\tany',
 'B-Restaurant_Name\tbeanery',
 'O\trestaurants',
 'O\tat',
 'O\tthe',
 'B-Location\tnorth',
 'I-Location\tend',
 '',
 'O\tany',
 'B-Cuisine\tbeanery',
 'O\trestaurants',
 'O\ton',
 'B-Location\twestborough',
 '',
 'O\tany',
 'B-Dish\tbeef',
 'O\tcuisine',
 'O\trestaurants',
 'O\twith',
 'B-Amenity\tbrewpub',
 'O\tand',
 'B-Price\tgreat',
 'O\tprices',
 '',
 'O\tany',
 'B-Amenity\tbuffet',
 'I-Amenity\tstyle',
 'O\trestaurant',
 'B-Location\tin',
 'I-Location\tmy',
 'I-Location\tarea',
 '',
 'O\tany',
 'B-Amenity\tbusiness',
 'I-Amenity\teateries',
 'O\twith',
 'B-Amenity\tgreat',
 'I-Amenity\tportions',
 '',
 'O\tany',
 'B-Rating\tbusy',
 'O\trestaurants',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tany',
 'B-Cuisine\tcali',
 'I-Cuisine\teateries',
 'B-Hours\topen',
 'I-Hours\tat',
 'I-Hours\t11',
 'I-Hours\tam',
 '',
 'O\tany',
 'O\tchance',
 'O\ti',
 'O\tcan',
 'O\tget',
 'O\ta',
 'B-Amenity\treservation',
 'O\tat',
 'O\tthat',
 'B-Amenity\tfine',
 'I-Amenity\tdining',
 'O\tplace',
 'O\tthats',
 'O\tthe',
 'B-Rating\ttop',
 'I-Rating\trated',
 'I-Rating\ton',
 'I-Rating\ttripadvisor',
 '',
 'O\tany',
 'B-Price\tcheap',
 'O\tplaces',
 'O\ton',
 'B-Location\tmiddleboro',
 '',
 'O\tany',
 'B-Price\tcheap',
 'O\trestaurants',
 'B-Hours\topen',
 'I-Hours\tbefore',
 'I-Hours\t8',
 'I-Hours\ta',
 'I-Hours\tm',
 '',
 'O\tany',
 'B-Price\tcheap',
 'B-Cuisine\tspanish',
 'O\tplaces',
 '',
 'O\tany',
 'B-Rating\tcrowd',
 'I-Rating\tpleasing',
 'O\trestaurants',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tany',
 'B-Cuisine\tdeli',
 'O\twith',
 'B-Amenity\tcatering',
 'I-Amenity\tservices',
 '',
 'O\tany',
 'B-Cuisine\tfamily',
 'O\trestaurant',
 'B-Location\tnearby',
 '',
 'O\tany',
 'B-Cuisine\tfast',
 'I-Cuisine\tfood',
 'B-Location\tnearby',
 '',
 'O\tany',
 'B-Cuisine\tfast',
 'I-Cuisine\tfood',
 'O\tplaces',
 'B-Hours\topen',
 'I-Hours\tthis',
 'I-Hours\tlate',
 '',
 'O\tany',
 'B-Cuisine\tfast',
 'I-Cuisine\tfood',
 'O\trestaurants',
 'B-Location\tnearby',
 '',
 'O\tany',
 'B-Cuisine\tfastfood',
 'B-Location\tnearby',
 '',
 'O\tany',
 'O\tfood',
 'B-Cuisine\tlow',
 'I-Cuisine\tfat',
 'O\tfood',
 'O\tresteraunt',
 '',
 'O\tany',
 'O\tfood',
 'B-Location\twithin',
 'I-Location\t5',
 'I-Location\tmiles',
 '',
 'O\tany',
 'B-Cuisine\tgerman',
 'O\tcuisine',
 'B-Cuisine\tdiners',
 'O\taround',
 'O\twith',
 'B-Amenity\tno',
 'I-Amenity\tsmoking',
 'O\tpermitted',
 '',
 'O\tany',
 'B-Rating\tgood',
 'B-Cuisine\tice',
 'I-Cuisine\tcream',
 'O\tplaces',
 'B-Location\taround',
 '',
 'O\tany',
 'B-Rating\tgood',
 'B-Cuisine\tsteak',
 'I-Cuisine\thouses',
 'B-Location\taround',
 'O\tme',
 '',
 'O\tany',
 'B-Restaurant_Name\tihops',
 'B-Location\taround',
 '',
 'O\tany',
 'B-Restaurant_Name\tinernational',
 'B-Dish\tbrownies',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tany',
 'B-Amenity\tkid',
 'I-Amenity\tfriendly',
 'O\trestaurants',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tany',
 'B-Hours\tlate',
 'I-Hours\tnight',
 'B-Cuisine\tdiners',
 'O\tfeaturing',
 'B-Dish\tsake',
 '',
 'O\tany',
 'B-Amenity\tnice',
 'I-Amenity\tdine',
 'I-Amenity\tin',
 'O\trestaurants',
 'B-Location\tnext',
 'I-Location\tto',
 'I-Location\there',
 '',
 'O\tany',
 'B-Price\tnicely',
 'O\tpriced',
 'O\tplaces',
 'B-Location\tin',
 'I-Location\tharvard',
 'O\twith',
 'B-Rating\tnice',
 'I-Rating\ttoppings',
 '',
 'O\tany',
 'O\tof',
 'O\tthe',
 'B-Restaurant_Name\tlandrys',
 'O\trestaurants',
 'O\toffer',
 'B-Amenity\tcarry',
 'I-Amenity\tout',
 'B-Hours\tuntil',
 'I-Hours\tat',
 'I-Hours\tleast',
 'I-Hours\t9',
 'I-Hours\tpm',
 '',
 'O\tany',
 'O\tpho',
 'B-Cuisine\thoa',
 'O\trestaurants',
 'O\twith',
 'B-Hours\tlate',
 'I-Hours\tnight',
 'I-Hours\tdining',
 '',
 'O\tany',
 'O\tplace',
 'B-Location\taround',
 'O\tthat',
 'O\tserves',
 'B-Dish\tsandwichs',
 'O\ton',
 'O\ttheir',
 'B-Hours\tlunch',
 'O\tmenu',
 '',
 'O\tany',
 'O\tplace',
 'O\taround',
 'O\tthat',
 'O\tserves',
 'B-Cuisine\tvegan',
 'O\tfood',
 'O\toptions',
 '',
 'O\tany',
 'O\tplace',
 'B-Rating\tgood',
 'O\tto',
 'O\teat',
 'B-Location\tnearby',
 '',
 'O\tany',
 'O\tplace',
 'O\tto',
 'O\teat',
 'B-Location\tnearby',
 'O\tthat',
 'O\ttakes',
 'B-Amenity\ttravelers',
 'I-Amenity\tchecks',
 '',
 'O\tany',
 'O\tplaces',
 'B-Location\talong',
 'I-Location\tthis',
 'I-Location\troad',
 'O\tserve',
 'B-Dish\tchips',
 '',
 'O\tany',
 'O\tplaces',
 'O\tin',
 'B-Location\tharvard',
 'I-Location\tsquare',
 'O\twhere',
 'O\ti',
 'O\tcan',
 'O\tget',
 'B-Dish\tpotato',
 'I-Dish\tpie',
 'O\tand',
 'B-Amenity\tsee',
 'I-Amenity\tsome',
 'I-Amenity\tcelebrities',
 '',
 'O\tany',
 'B-Price\treasonable',
 'O\tpriced',
 'B-Cuisine\tchowder',
 'O\trestaurants',
 'O\toffering',
 'B-Amenity\tgroup',
 'I-Amenity\tdining',
 '',
 'O\tany',
 'O\trestaurant',
 'B-Location\tclose',
 'I-Location\tby',
 'O\tthat',
 'O\tserves',
 'B-Cuisine\tvegan',
 'O\tdish',
 'O\tand',
 'O\tits',
 'B-Price\taffordable',
 '',
 'O\tany',
 'O\trestaurant',
 'O\tthat',
 'B-Hours\topens',
 'I-Hours\t24',
 'I-Hours\thours',
 '',
 'O\tany',
 'O\trestaurants',
 'O\taround',
 'O\tfeaturing',
 'B-Cuisine\tbrunch',
 'O\ton',
 'B-Location\thovendon',
 'I-Location\tavenue',
 '',
 'O\tany',
 'O\trestaurants',
 'B-Location\taround',
 'I-Location\tfour',
 'I-Location\tmiles',
 'I-Location\tfrom',
 'I-Location\there',
 'O\twith',
 'B-Amenity\tprivate',
 'I-Amenity\trooms',
 '',
 'O\tany',
 'O\trestaurants',
 'O\taround',
 'B-Location\tgovernment',
 'I-Location\tcenter',
 'O\twith',
 'B-Price\tgreat',
 'O\tprices',
 '',
 'O\tany',
 'O\trestaurants',
 'B-Location\taround',
 'I-Location\tsacramento',
 'O\twith',
 'B-Amenity\tfireplace',
 'O\tand',
 'B-Amenity\tgreat',
 'I-Amenity\tatmosphere',
 '',
 'O\tany',
 'O\trestaurants',
 'B-Location\taround',
 'O\tthat',
 'O\tserve',
 'B-Cuisine\torganic',
 'O\tfoods',
 '',
 'O\tany',
 'O\trestaurants',
 'B-Location\ttake',
 'I-Location\tchecks',
 '',
 'O\tany',
 'O\trestaurants',
 'O\tthat',
 'O\tserve',
 'B-Dish\tfrench',
 'I-Dish\tfries',
 'O\tand',
 'O\thave',
 'O\ta',
 'B-Amenity\tpatio',
 'B-Location\tnearby',
 '',
 'O\tany',
 'B-Cuisine\tsouthwestern',
 'O\tcuisine',
 'O\trestaurants',
 'O\tfeaturing',
 'B-Amenity\tromantic',
 'I-Amenity\tdining',
 'B-Location\tnearby',
 '',
 'O\tany',
 'B-Cuisine\tspanish',
 'O\trestaurants',
 'O\tin',
 'B-Location\tjamaica',
 'I-Location\tplain',
 'B-Hours\topen',
 'I-Hours\tin',
 'I-Hours\tthe',
 'I-Hours\tmorning',
 '',
 'O\tany',
 'B-Rating\tsuggestions',
 'O\ton',
 'O\twhat',
 'O\tto',
 'O\teat',
 '',
 'O\tany',
 'B-Cuisine\ttapas',
 'O\tplaces',
 'O\twith',
 'B-Amenity\tdrink',
 'I-Amenity\tspecials',
 '',
 'O\tany',
 'B-Cuisine\tunique',
 'O\tfoods',
 'O\there',
 '',
 'O\tanybody',
 'O\tserve',
 'B-Dish\tboardwalk',
 'I-Dish\tfries',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tanyplace',
 'O\ti',
 'O\tcan',
 'O\tget',
 'O\tsome',
 'O\tgood',
 'B-Dish\tpita',
 'I-Dish\tbread',
 'O\tthats',
 'B-Location\tnot',
 'I-Location\tmore',
 'I-Location\tthan',
 'I-Location\t4',
 'I-Location\tmiles',
 'O\tout',
 '',
 'O\tanything',
 'B-Rating\tgood',
 'O\tto',
 'O\teat',
 'B-Location\twithin',
 'I-Location\t10',
 'I-Location\tmiles',
 '',
 'O\tanything',
 'O\twith',
 'B-Amenity\tgroup',
 'I-Amenity\tseating',
 '',
 'O\tanywhere',
 'O\ti',
 'O\tcan',
 'O\tget',
 'O\ta',
 'O\ttasty',
 'O\tand',
 'B-Price\tcheap',
 'B-Dish\tnoodle',
 'I-Dish\tdish',
 '',
 'O\tanywhere',
 'O\tthats',
 'B-Amenity\tnot',
 'I-Amenity\tcrowded',
 'O\tbefore',
 'O\tthe',
 'O\tgame',
 'O\twhere',
 'O\ti',
 'O\tcan',
 'O\tget',
 'O\ta',
 'O\tbite',
 '',
 'B-Restaurant_Name\tapple',
 'I-Restaurant_Name\tbs',
 'O\tresturant',
 'B-Location\tin',
 'I-Location\ttown',
 '',
 'B-Cuisine\tarabic',
 'O\tcuisine',
 'B-Location\tnear',
 'I-Location\tme',
 '',
 'O\tare',
 'O\tany',
 'B-Cuisine\tdoughnut',
 'O\tshops',
 'B-Hours\topen',
 'I-Hours\tright',
 'I-Hours\tnow',
 '',
 'O\tare',
 'O\tany',
 'B-Cuisine\tvegetarian',
 'O\trestaurants',
 'B-Location\twithin',
 'I-Location\t5',
 'I-Location\tblocks',
 'O\tof',
 'O\there',
 '',
 'O\tare',
 'B-Amenity\tchildren',
 'I-Amenity\tallowed',
 'O\tin',
 'B-Restaurant_Name\tmi',
 'I-Restaurant_Name\tpiacis',
 '',
 'O\tare',
 'B-Restaurant_Name\trivertown',
 'I-Restaurant_Name\tcoffee',
 'I-Restaurant_Name\tco',
 'O\tor',
 'B-Restaurant_Name\taromas',
 'I-Restaurant_Name\tcoffee',
 'I-Restaurant_Name\tbar',
 'O\texpensive',
 '',
 'O\tare',
 'B-Restaurant_Name\tsebastians',
 'O\trestaurants',
 'B-Amenity\tportions',
 'I-Amenity\tbig',
 '',
 'O\tare',
 'O\tthan',
 'O\tany',
 'B-Cuisine\tsushi',
 'O\trestaurants',
 'O\ton',
 'O\tthe',
 'B-Location\tnorth',
 'I-Location\tside',
 'I-Location\tof',
 'I-Location\ttown',
 'O\tand',
 'O\ti',
 'O\tneed',
 'O\tto',
 'O\tknow',
 'O\ttheir',
 'O\tphone',
 'O\tnumber',
 'O\tand',
 'O\tdirections',
 '',
 'O\tare',
 'O\tthe',
 'O\tany',
 'B-Cuisine\tvegetarian',
 'O\trestaurants',
 'O\tin',
 'B-Location\tcleveland',
 'I-Location\tpark',
 '',
 'O\tare',
 'O\tthe',
 'O\tproportions',
 'O\tbig',
 'O\tor',
 'O\tsmall',
 '',
 'O\tare',
 'O\tthe',
 'O\treviews',
 'O\tgood',
 'O\tfor',
 'B-Restaurant_Name\tchichis',
 'O\tin',
 'B-Location\tgona',
 '',
 'O\tare',
 'O\tthe',
 'O\treviews',
 'O\tgood',
 'O\tfor',
 'B-Restaurant_Name\tdonovans',
 'I-Restaurant_Name\trooftop',
 'I-Restaurant_Name\tgrill',
 '',
 'O\tare',
 'O\tthe',
 'B-Amenity\tservers',
 'I-Amenity\tattractive',
 '',
 'O\tare',
 'O\ttheir',
 'O\tany',
 'B-Location\tplaces',
 'O\tto',
 'O\teat',
 'O\tnear',
 'O\tmy',
 'B-Location\tlocation',
 '',
 'O\tare',
 'O\tthere',
 'B-Price\taffordable',
 'O\trestaurants',
 'O\tin',
 'B-Location\tkingston',
 'B-Hours\topen',
 'I-Hours\tuntil',
 'I-Hours\t11',
 'I-Hours\tpm',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Hours\t24',
 'I-Hours\thour',
 'B-Cuisine\tdiners',
 'O\taround',
 'B-Location\there',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Hours\t24',
 'I-Hours\thour',
 'B-Cuisine\tdiners',
 'B-Location\tnear',
 'I-Location\tby',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Hours\t24',
 'I-Hours\thour',
 'O\trestaurants',
 'B-Location\tnearby',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Rating\t4',
 'I-Rating\tstar',
 'B-Cuisine\tseafood',
 'O\trestaurants',
 'B-Location\twithin',
 'I-Location\t10',
 'I-Location\tmiles',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Rating\t5',
 'I-Rating\tstar',
 'O\trestaurants',
 'B-Location\tnear',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Price\taffordable',
 'B-Cuisine\tmeat',
 'O\tserving',
 'O\tvenues',
 'B-Location\twithin',
 'I-Location\tfive',
 'I-Location\tmiles',
 'I-Location\tof',
 'I-Location\there',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Price\taffordable',
 'O\tsteak',
 'O\tplaces',
 'O\tin',
 'O\tlittleton',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Amenity\tall',
 'I-Amenity\tyou',
 'I-Amenity\tcan',
 'I-Amenity\teat',
 'B-Cuisine\tsushi',
 'B-Amenity\tbuffets',
 'O\tin',
 'B-Location\twestbury',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Cuisine\tamerican',
 'O\trestaurants',
 'B-Location\tin',
 'I-Location\tarea',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Cuisine\tamerican',
 'O\trestaurants',
 'O\tthat',
 'O\tare',
 'O\talso',
 'B-Amenity\tcarry',
 'I-Amenity\tout',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Restaurant_Name\tarbys',
 'B-Location\tin',
 'I-Location\tthis',
 'I-Location\tarea',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Restaurant_Name\tarbys',
 'B-Location\twith',
 'I-Location\tin',
 'I-Location\tten',
 'I-Location\tmiles',
 'I-Location\tof',
 'I-Location\there',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Cuisine\tasian',
 'O\trestaurants',
 'B-Location\tclose',
 'I-Location\tby',
 '',
 'O\tare',
 'O\tthere',
 'O\tany',
 'B-Cuisine\tauthentic',
 'I-Cuisine\tgreek',
 'O\trestaurants',
 'O\tthat',
 'O\tserve',
 'B-Dish\tgyros',
 'B-Location\taround',
 'I-Location\there',
 '',
 'O\tare',
 'O\tthere',
 ...]

In [9]:
train_tokens = []
train_tags = []

temp_tags = []
temp_tokens = []

for line in response:
  if line != "":
    tag,token = line.strip().split("\t")
    temp_tags.append(tag)
    temp_tokens.append(token)
  else:
    train_tokens.append(temp_tokens)
    train_tags.append(temp_tags)
    temp_tokens,temp_tags = [],[]

In [10]:
train_tags

[['B-Rating', 'I-Rating', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O'],
 ['B-Rating', 'I-Rating', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'B-Restaurant_Name', 'I-Restaurant_Name', 'O', 'B-Price', 'O'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'B-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O', 'O', 'O', 'O', 'B-Dish', 'I-Dish', 'I-Dish', 'I-Dish'],
 ['O', 'O', 'O', 'O', 'B-Rating', 'B-Amenity', 'I-Amenity'],
 ['O', 'B-Dish', 'O', 'O', 'O', 'O'],
 ['O', 'B-Cuisine', 'O', 'O', 'O', 'O'],
 ['O', 'B-Dish', 'O', 'O', 'O'],
 ['O', 'B-Dish', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'B-Price',
  'B-Rating',
  'O',
  'B-Rating',
  'B-Cuisine',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'B-Price',
  'O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name',
  'O',
  'B-Hours',
  'B-Price',
  'I-Price'],
 ['O', 'O', 'O', 'B-Location', 'B-Restaurant_Name', 'I-Restaurant_Name'],
 ['B-Hours', 'I-Hours', 'I-Hours'],
 ['O', 'O', 'O', 'O', 'O', 'B-Dish', 'I-Dish', 'I-Dish', 'O', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'O', 'B-Dish'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'B-Dish',
  'I-Dish',
  'O',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O', 'O', 'O', 'O', 'O', 'B-Rating', 'B-Dish', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'B-Amenity', 'B-Cuisine', 'O'],
 ['O',
  'O',
  'B-Rating',
  'B-Dish',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Restaurant_Name', 'B-Hours'],
 ['B-Cuisine', 'O', 'O', 'B-Rating'],
 ['B-Amenity', 'I-Amenity'],
 ['O', 'B-Amenity', 'I-Amenity', 'B-Cuisine', 'O'],
 ['O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours'],
 ['O', 'B-Restaurant_Name', 'O', 'O', 'O', 'B-Location', 'I-Location'],
 ['O', 'B-Cuisine', 'O', 'O', 'B-Location'],
 ['O', 'B-Dish', 'O', 'O', 'O', 'B-Amenity', 'O', 'B-Price', 'O'],
 ['O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'B-Amenity', 'I-Amenity', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'B-Rating', 'O', 'B-Location', 'I-Location'],
 ['O', 'B-Cuisine', 'I-Cuisine', 'B-Hours', 'I-Hours', 'I-Hours', 'I-Hours'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Amenity',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'O',
  'B-Rating',
  'I-Rating',
  'I-Rating',
  'I-Rating'],
 ['O', 'B-Price', 'O', 'O', 'B-Location'],
 ['O', 'B-Price', 'O', 'B-Hours', 'I-Hours', 'I-Hours', 'I-Hours', 'I-Hours'],
 ['O', 'B-Price', 'B-Cuisine', 'O'],
 ['O', 'B-Rating', 'I-Rating', 'O', 'B-Location', 'I-Location'],
 ['O', 'B-Cuisine', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'B-Cuisine', 'O', 'B-Location'],
 ['O', 'B-Cuisine', 'I-Cuisine', 'B-Location'],
 ['O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Hours', 'I-Hours', 'I-Hours'],
 ['O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Location'],
 ['O', 'B-Cuisine', 'B-Location'],
 ['O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'O'],
 ['O', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'B-Cuisine', 'O', 'B-Cuisine', 'O', 'O', 'B-Amenity', 'I-Amenity', 'O'],
 ['O', 'B-Rating', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Location'],
 ['O', 'B-Rating', 'B-Cuisine', 'I-Cuisine', 'B-Location', 'O'],
 ['O', 'B-Restaurant_Name', 'B-Location'],
 ['O', 'B-Restaurant_Name', 'B-Dish', 'B-Location', 'I-Location'],
 ['O', 'B-Amenity', 'I-Amenity', 'O', 'B-Location', 'I-Location'],
 ['O', 'B-Hours', 'I-Hours', 'B-Cuisine', 'O', 'B-Dish'],
 ['O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'B-Price',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'B-Rating',
  'I-Rating'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours'],
 ['O', 'O', 'B-Cuisine', 'O', 'O', 'B-Hours', 'I-Hours', 'I-Hours'],
 ['O', 'O', 'B-Location', 'O', 'O', 'B-Dish', 'O', 'O', 'B-Hours', 'O'],
 ['O', 'O', 'O', 'O', 'O', 'B-Cuisine', 'O', 'O'],
 ['O', 'O', 'B-Rating', 'O', 'O', 'B-Location'],
 ['O', 'O', 'O', 'O', 'B-Location', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'O', 'B-Location', 'I-Location', 'I-Location', 'O', 'B-Dish'],
 ['O',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'O',
  'O',
  'O',
  'B-Dish',
  'I-Dish',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O', 'B-Price', 'O', 'B-Cuisine', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Price'],
 ['O', 'O', 'O', 'B-Hours', 'I-Hours', 'I-Hours'],
 ['O', 'O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O', 'O', 'O', 'B-Location', 'I-Location', 'O', 'B-Price', 'O'],
 ['O',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'B-Amenity',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O', 'O', 'B-Location', 'O', 'O', 'B-Cuisine', 'O'],
 ['O', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'O',
  'B-Dish',
  'I-Dish',
  'O',
  'O',
  'O',
  'B-Amenity',
  'B-Location'],
 ['O', 'B-Cuisine', 'O', 'O', 'O', 'B-Amenity', 'I-Amenity', 'B-Location'],
 ['O',
  'B-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours'],
 ['O', 'B-Rating', 'O', 'O', 'O', 'O'],
 ['O', 'B-Cuisine', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'B-Cuisine', 'O', 'O'],
 ['O', 'O', 'B-Dish', 'I-Dish', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Dish',
  'I-Dish',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'O'],
 ['O', 'B-Rating', 'O', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Price', 'B-Dish', 'I-Dish'],
 ['O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['B-Restaurant_Name', 'I-Restaurant_Name', 'O', 'B-Location', 'I-Location'],
 ['B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'B-Cuisine', 'O', 'B-Hours', 'I-Hours', 'I-Hours'],
 ['O',
  'O',
  'B-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'O',
  'O'],
 ['O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name',
  'O'],
 ['O', 'B-Restaurant_Name', 'O', 'B-Amenity', 'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'O', 'O', 'B-Restaurant_Name', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'O', 'O', 'B-Location', 'O', 'O', 'O', 'O', 'B-Location'],
 ['O',
  'O',
  'B-Price',
  'O',
  'O',
  'B-Location',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours'],
 ['O', 'O', 'O', 'B-Hours', 'I-Hours', 'B-Cuisine', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'B-Cuisine',
  'B-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Hours', 'I-Hours', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'I-Rating',
  'B-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'I-Rating', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Price', 'O', 'O', 'O', 'O'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'B-Cuisine',
  'B-Amenity',
  'O',
  'B-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'O',
  'B-Dish',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'O',
  'O',
  'O',
  'B-Cuisine',
  'O'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Hours',
  'O',
  'O',
  'O',
  'B-Dish',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Amenity', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'B-Location',
  'I-Location',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Dish',
  'O',
  'O',
  'B-Location',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'B-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Restaurant_Name', 'I-Restaurant_Name', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location',
  'O',
  'O'],
 ['O',
  'O',
  'O',
  'B-Dish',
  'O',
  'B-Dish',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Amenity', 'O', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'O',
  'O',
  'B-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Location',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'B-Cuisine',
  'I-Cuisine',
  'I-Cuisine',
  'B-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Rating',
  'I-Rating',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Price', 'B-Cuisine', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Price', 'B-Cuisine', 'O', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Price', 'B-Cuisine', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Cuisine',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'B-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Cuisine',
  'B-Location',
  'I-Location',
  'I-Location',
  'O',
  'B-Rating',
  'I-Rating'],
 ['O', 'O', 'O', 'B-Price', 'O', 'O', 'O', 'B-Location'],
 ['O', 'O', 'O', 'B-Price', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Location',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'O',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Restaurant_Name', 'I-Restaurant_Name', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'B-Amenity', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'O',
  'B-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Restaurant_Name',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location'],
 ['O',
  'O',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'B-Amenity',
  'I-Amenity'],
 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Hours', 'O', 'B-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Amenity', 'I-Amenity', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'B-Location',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'B-Hours',
  'I-Hours',
  'I-Hours'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'O',
  'B-Dish',
  'I-Dish',
  'I-Dish',
  'B-Hours',
  'I-Hours'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Price',
  'B-Rating',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Price', 'O', 'B-Location', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'O', 'O', 'B-Price', 'I-Price', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'B-Price',
  'O'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'B-Cuisine',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'O', 'B-Amenity', 'O', 'O', 'O', 'B-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Hours'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location',
  'O',
  'O'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'O', 'B-Amenity', 'I-Amenity'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Hours', 'I-Hours'],
 ['O', 'O', 'O', 'B-Cuisine', 'I-Cuisine', 'O', 'B-Hours', 'I-Hours'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'B-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'B-Location',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'I-Amenity',
  'B-Location',
  'I-Location',
  'I-Location',
  'I-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'I-Rating',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Dish',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'I-Rating', 'O', 'O', 'O', 'B-Location'],
 ['O', 'O', 'O', 'B-Rating', 'I-Rating', 'O', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'B-Restaurant_Name',
  'O',
  'O',
  'B-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Amenity',
  'I-Amenity',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Location',
  'O',
  'B-Amenity',
  'I-Amenity',
  'I-Amenity'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'B-Location'],
 ['O', 'O', 'O', 'B-Rating', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'B-Cuisine', 'O', 'B-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'O',
  'O',
  'O',
  'B-Cuisine',
  'O',
  'B-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'I-Hours',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'O',
  'O',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'O', 'O', 'B-Dish', 'I-Dish', 'O', 'O'],
 ['O', 'O', 'O', 'O', 'B-Dish', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O', 'O', 'O', 'B-Rating', 'O', 'O', 'B-Amenity', 'I-Amenity', 'O'],
 ['O', 'O', 'O', 'B-Rating', 'O', 'B-Location', 'I-Location', 'I-Location'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'O',
  'B-Location',
  'I-Location',
  'O',
  'O',
  'O',
  'B-Price',
  'I-Price',
  'O',
  'O',
  'B-Hours',
  'I-Hours'],
 ['O',
  'O',
  'O',
  'B-Rating',
  'I-Rating',
  'O',
  'B-Restaurant_Name',
  'I-Restaurant_Name',
  'I-Restaurant_Name'],
 ['O', 'O', 'O', 'B-Rating', 'B-Cuisine', 'O', 'B-Location'],
 ['O', 'O', 'O', 'B-Cuisine', 'O', 'O', 'B-Location'],
 ['O',
  'O',
  'O',
  'B-Cuisine',
  'I-Cuisine',
  'I-Cuisine',
  'I-Cuisine',
  'B-Location',
  'I-Location'],
 ['O',
  'O',
  'O',

In [11]:
len(train_tokens),len(train_tags)

(7659, 7659)

In [12]:
response = requests.get("https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/mit_restaurant_search_ner/test.bio")
response = response.text
response = response.splitlines()
test_tokens = []
test_tags = []

temp_tags = []
temp_tokens = []

for line in response:
  if line != "":
    tag,token = line.strip().split("\t")
    temp_tags.append(tag)
    temp_tokens.append(token)
  else:
    test_tokens.append(temp_tokens)
    test_tags.append(temp_tags)
    temp_tokens,temp_tags = [],[]

len(test_tokens),len(test_tags)

(1520, 1520)

HUGGING face data prep

In [13]:
from datasets import Dataset,DatasetDict

df = pd.DataFrame(data={"tokens":train_tokens,"ner_tags_str":train_tags})
train = Dataset.from_pandas(df)

df = pd.DataFrame(data={"tokens":test_tokens,"ner_tags_str":test_tags})
test = Dataset.from_pandas(df)


dataset = DatasetDict({'train':train,'test':test,'validation':test})
dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 7659
    })
    test: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 1520
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 1520
    })
})

In [14]:
dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 7659
    })
    test: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 1520
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags_str'],
        num_rows: 1520
    })
})

In [15]:
dataset['train'][0]

{'tokens': ['2', 'start', 'restaurants', 'with', 'inside', 'dining'],
 'ner_tags_str': ['B-Rating', 'I-Rating', 'O', 'O', 'B-Amenity', 'I-Amenity']}

In [16]:
unique_tags = set()
for tag in dataset['train']['ner_tags_str']:
    unique_tags.update(tag)
unique_tags = list(set([x[2:] for x in list(unique_tags) if x!='O']))
tag2index = {"O": 0}
for i, tag in enumerate(unique_tags):
    tag2index[f'B-{tag}'] = len(tag2index)
    tag2index[f'I-{tag}'] = len(tag2index)

index2tag = {v:k for k,v in tag2index.items()}

In [17]:
tag2index,index2tag

({'O': 0,
  'B-Cuisine': 1,
  'I-Cuisine': 2,
  'B-Restaurant_Name': 3,
  'I-Restaurant_Name': 4,
  'B-Hours': 5,
  'I-Hours': 6,
  'B-Location': 7,
  'I-Location': 8,
  'B-Rating': 9,
  'I-Rating': 10,
  'B-Dish': 11,
  'I-Dish': 12,
  'B-Amenity': 13,
  'I-Amenity': 14,
  'B-Price': 15,
  'I-Price': 16},
 {0: 'O',
  1: 'B-Cuisine',
  2: 'I-Cuisine',
  3: 'B-Restaurant_Name',
  4: 'I-Restaurant_Name',
  5: 'B-Hours',
  6: 'I-Hours',
  7: 'B-Location',
  8: 'I-Location',
  9: 'B-Rating',
  10: 'I-Rating',
  11: 'B-Dish',
  12: 'I-Dish',
  13: 'B-Amenity',
  14: 'I-Amenity',
  15: 'B-Price',
  16: 'I-Price'})

In [18]:
dataset = dataset.map(lambda example: {"ner_tags": [tag2index[tag] for tag in example['ner_tags_str']]})

Map:   0%|          | 0/7659 [00:00<?, ? examples/s]

Map:   0%|          | 0/1520 [00:00<?, ? examples/s]

Map:   0%|          | 0/1520 [00:00<?, ? examples/s]

In [19]:
dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags_str', 'ner_tags'],
        num_rows: 7659
    })
    test: Dataset({
        features: ['tokens', 'ner_tags_str', 'ner_tags'],
        num_rows: 1520
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags_str', 'ner_tags'],
        num_rows: 1520
    })
})

MODEL BUILDING

In [20]:
from transformers import AutoTokenizer

In [21]:
model_ckpt = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [22]:
dataset['train'][2]

{'tokens': ['5', 'star', 'resturants', 'in', 'my', 'town'],
 'ner_tags_str': ['B-Rating',
  'I-Rating',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 'ner_tags': [9, 10, 0, 7, 8, 8]}

In [23]:
input = dataset['train'][2]['tokens']
output = tokenizer(input, is_split_into_words=True)
tokenizer.convert_ids_to_tokens(output.input_ids)

['[CLS]', '5', 'star', 'rest', '##ura', '##nts', 'in', 'my', 'town', '[SEP]']

In [24]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples['tokens'], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples['ner_tags']):
        word_ids = tokenized_inputs.word_ids(batch_index=i)

        previous_word_idx = None
        label_ids = []

        for word_idx in word_ids:
            # if id=-100 then loss is not calculated
            if word_idx is None:
                label_ids.append(-100)

            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])

            else:
                label_ids.append(-100)

            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs['labels'] = labels

    return tokenized_inputs

In [25]:
tokenized_dataset = dataset.map(tokenize_and_align_labels, batched=True)

Map:   0%|          | 0/7659 [00:00<?, ? examples/s]

Map:   0%|          | 0/1520 [00:00<?, ? examples/s]

Map:   0%|          | 0/1520 [00:00<?, ? examples/s]

In [26]:
tokenized_dataset['train'][2]

{'tokens': ['5', 'star', 'resturants', 'in', 'my', 'town'],
 'ner_tags_str': ['B-Rating',
  'I-Rating',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 'ner_tags': [9, 10, 0, 7, 8, 8],
 'input_ids': [101, 1019, 2732, 2717, 4648, 7666, 1999, 2026, 2237, 102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'labels': [-100, 9, 10, 0, -100, -100, 7, 8, 8, -100]}

In [27]:
dataset['train'][2]

{'tokens': ['5', 'star', 'resturants', 'in', 'my', 'town'],
 'ner_tags_str': ['B-Rating',
  'I-Rating',
  'O',
  'B-Location',
  'I-Location',
  'I-Location'],
 'ner_tags': [9, 10, 0, 7, 8, 8]}

## Data Collation and Metrics

In [28]:
!pip install seqeval
!pip install evaluate

Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from seqeval) (2.0.2)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.12/dist-packages (from seqeval) (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=f52251cf017246e2aba9ad5afa3ddaa92737f14d2e4091341a42c82c7d6818b4
  Stored in directory: /root/.cache/pip/wheels/5f/b8/73/0b2c1a76b701a677653dd79ece07cfabd7457989dbfbdcd8d7
Successfully built seqeval
Installing collected packages: seqeval
Successfully installed seqeval-1.2.2
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.3.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (23.0.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [29]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

In [30]:
import evaluate
import numpy as np

metric = evaluate.load('seqeval')
label_names = list(tag2index)

def compute_metrics(eval_preds):
    logits, labels = eval_preds

    predictions = np.argmax(logits, axis=-1)
    true_labels = [[label_names[l] for l in label if l!=-100] for label in labels]

    true_predictions = [[label_names[p] for p, l in zip(prediction, label) if l != -100]
                        for prediction, label in zip(predictions, labels)]

    all_metrics = metric.compute(predictions=true_predictions, references=true_labels)

    return {
        "precision": all_metrics['overall_precision'],
        'recall': all_metrics['overall_recall'],
        'f1': all_metrics['overall_f1'],
        'accuracy': all_metrics['overall_accuracy'],
    }

Downloading builder script: 0.00B [00:00, ?B/s]

MODEL TRAINING

In [31]:
from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(model_ckpt, id2label=index2tag, label2id=tag2index)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [32]:
from transformers import TrainingArguments, Trainer

In [33]:
args = TrainingArguments("finetuned-ner", eval_strategy='epoch',
                         save_strategy='epoch',
                         learning_rate=2e-5,
                         num_train_epochs=10,
                         weight_decay=0.01)

In [34]:
trainer = Trainer(model=model, args=args,
                  train_dataset=tokenized_dataset['train'],
                  eval_dataset=tokenized_dataset['validation'],
                  data_collator=data_collator,
                  compute_metrics=compute_metrics)

In [35]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=9580, training_loss=0.15770617601518094, metrics={'train_runtime': 441.9576, 'train_samples_per_second': 173.297, 'train_steps_per_second': 21.676, 'total_flos': 350652911199822.0, 'train_loss': 0.15770617601518094, 'epoch': 10.0})

In [36]:
trainer.save_model("ner_distilbert")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [37]:
from transformers import pipeline

checkpoint = "ner_distilbert"
pipe = pipeline('token-classification', model=checkpoint, aggregation_strategy='simple')

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

In [38]:
pipe("which restaurant serves the best shushi in new york?")

[{'entity_group': 'Rating',
  'score': np.float32(0.9958335),
  'word': 'best',
  'start': 28,
  'end': 32},
 {'entity_group': 'Dish',
  'score': np.float32(0.9710214),
  'word': 'shushi',
  'start': 33,
  'end': 39},
 {'entity_group': 'Location',
  'score': np.float32(0.9907137),
  'word': 'new york',
  'start': 43,
  'end': 51}]